### ISSUE TITLE
Improve performance at the presence of malware scanners

### ISSUE THREAD

**Issue by ecki** [microsoft/java-wdb#32]
## Summary
Java run- and build-times environment on Windows are especially badly affected by on-access malware scanners which are mandatory on many organizations systems. The fact that large number of jar (aka zip) files are involved and exceptionally bad handling of reading and writing archives in most (all?) scanner products (including defender) really can slow a maven build or application server startup down.

### Basic example
Running a maven build on larger project, starting Eclipse or Karaf runtime...

### Motivation
Developers on Windows often have to stick to malware scanners and excludes are risky (and do not always help due to some heuristics of malware and endpoint scanners)

Unfortunatelly I don’t have a good answer how to fix it, maybe besides having new APIs for controlling scanners and simply providing a scanner which works better for those java workloads?

**Comment by ecki** [comment]
Hm, maybe related or duplicate of #9?

**Comment by brunoborges** [comment]
Indeed a duplicate. We will focus on #9.
